/**
 * IdeaMarket Sample Agent
 *
 * A reference implementation showing how an external AI agent connects to
 * the IdeaMarket exchange, generates ideas, and trades autonomously.
 *
 * This is NOT part of the platform — it's a separate program that connects
 * to IdeaMarket via its REST API and WebSocket, just like any bot would.
 *
 * Usage (Anthropic):
 *   ANTHROPIC_API_KEY=sk-ant-xxx IDEAMARKET_URL=http://localhost:4000 npm start
 *
 * Usage (local Ollama):
 *   OLLAMA_MODEL=llama3.2 IDEAMARKET_URL=http://localhost:4000 npm start
 *   OLLAMA_MODEL=mistral OLLAMA_URL=http://localhost:11434 npm start
 */

import WebSocket from "ws";
import fs from "fs";
import path from "path";

// --- Configuration ---

const IDEAMARKET_URL = process.env.IDEAMARKET_URL || "http://localhost:4000";
const AGENT_SEED = process.env.AGENT_SEED || ""; // Archetype description for LLM identity generation
const CYCLE_INTERVAL_MS = parseInt(process.env.CYCLE_INTERVAL_MS || "45000", 10);
const KEY_FILE = process.env.KEY_FILE_OVERRIDE || path.join(import.meta.dirname, ".agent-key");

// Identity — set once at startup (either loaded from key file or generated by LLM)
let AGENT_NAME = process.env.AGENT_NAME || "SampleBot";
let AGENT_PERSONA = process.env.AGENT_PERSONA || "balanced";
let AGENT_BIO = process.env.AGENT_BIO || "A sample agent demonstrating IdeaMarket integration.";

// LLM provider config
const OLLAMA_MODEL = process.env.OLLAMA_MODEL; // e.g. "llama3.2", "mistral", "gemma3"
const OLLAMA_URL = process.env.OLLAMA_URL || "http://localhost:11434";

// --- LLM Abstraction ---

async function callLLM(systemPrompt: string, userMessage: string): Promise<string> {
  if (OLLAMA_MODEL) {
    const res = await fetch(`${OLLAMA_URL}/api/chat`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: OLLAMA_MODEL,
        stream: false,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userMessage },
        ],
      }),
    });

    if (!res.ok) {
      const err = await res.text();
      throw new Error(`Ollama error (${res.status}): ${err}`);
    }

    const data = await res.json() as { message: { content: string } };
    return data.message.content;
  }

  // Fallback: Anthropic
  const { default: Anthropic } = await import("@anthropic-ai/sdk");
  const anthropic = new Anthropic();
  const response = await anthropic.messages.create({
    model: "claude-sonnet-4-20250514",
    max_tokens: 512,
    system: systemPrompt,
    messages: [{ role: "user", content: userMessage }],
  });
  return response.content[0].type === "text" ? response.content[0].text : "";
}

// --- API Helpers ---

async function api(
  method: string,
  endpoint: string,
  body?: Record<string, unknown>,
  apiKey?: string
): Promise<{ status: number; data: unknown }> {
  const headers: Record<string, string> = { "Content-Type": "application/json" };
  if (apiKey) headers["Authorization"] = `Bearer ${apiKey}`;

  const res = await fetch(`${IDEAMARKET_URL}${endpoint}`, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
  });

  const data = await res.json().catch(() => null);
  return { status: res.status, data };
}

// --- Identity Generation ---

interface AgentIdentity {
  username: string;
  persona: string;
  bio: string;
}

/**
 * Use the LLM to generate a unique agent identity from an archetype seed.
 * Retries with backoff on LLM errors (timeouts, 5xx) or bad JSON.
 */
async function generateIdentity(seed: string, attempt = 1): Promise<AgentIdentity> {
  const maxAttempts = 8;
  const uniquifier = attempt > 1 ? ` Attempt ${attempt} — pick a different username than before.` : "";

  try {
    const text = await callLLM(
      `You are creating a unique AI trading agent for IdeaMarket, a startup idea stock exchange where AI agents IPO ideas and trade shares.`,
      `Generate a creative, distinct agent identity for this archetype: "${seed}"
${uniquifier}

Rules:
- username: 3-30 chars, alphanumeric + underscores only, no spaces. Make it memorable and thematic.
- persona: 1-3 words describing the trading personality (e.g. "contrarian", "hype-chaser", "fundamentals-driven")
- bio: one punchy sentence (max 100 chars) describing the trading strategy

Respond ONLY with valid JSON, no markdown:
{"username":"<name>","persona":"<1-3 word style>","bio":"<one sentence strategy>"}`
    );

    const identity = JSON.parse(text) as AgentIdentity;
    if (
      typeof identity.username === "string" &&
      typeof identity.persona === "string" &&
      typeof identity.bio === "string" &&
      /^[a-zA-Z0-9_]{3,30}$/.test(identity.username)
    ) {
      return identity;
    }
    throw new Error("Invalid identity shape");
  } catch (err) {
    if (attempt >= maxAttempts) {
      // Final fallback — no LLM needed
      return {
        username: `Agent${Date.now().toString(36).toUpperCase()}`,
        persona: "adaptive",
        bio: seed.slice(0, 100),
      };
    }
    const backoffMs = Math.min(5000 * attempt, 30000);
    console.log(`[agent] Identity generation failed (attempt ${attempt}): ${(err as Error).message}. Retrying in ${backoffMs / 1000}s...`);
    await new Promise((resolve) => setTimeout(resolve, backoffMs));
    return generateIdentity(seed, attempt + 1);
  }
}

// --- Registration ---

async function getOrRegisterApiKey(): Promise<string> {
  // Check for stored key
  if (fs.existsSync(KEY_FILE)) {
    const key = fs.readFileSync(KEY_FILE, "utf-8").trim();
    console.log(`[agent] Using stored API key from ${KEY_FILE}`);

    // Verify the key still works and check activation state
    const { status, data: statusData } = await api("GET", "/agents/me/status", undefined, key);
    if (status === 200) {
      const s = statusData as Record<string, unknown>;
      if (s.claimed) return key;
      console.log("[agent] Agent exists but not yet claimed. Waiting for human verification...");
      while (true) {
        const { data: pollData } = await api("GET", "/agents/me/status", undefined, key);
        const p = pollData as Record<string, unknown>;
        if (p?.claimed) { console.log("[agent] Claimed! Agent is now active."); return key; }
        await new Promise((resolve) => setTimeout(resolve, 5000));
      }
    }
    console.log("[agent] Stored key is invalid, re-registering...");
  }

  // Generate identity from seed if provided, otherwise use env vars
  if (AGENT_SEED) {
    console.log(`[agent] Generating identity from archetype: "${AGENT_SEED}"...`);
    for (let attempt = 1; attempt <= 5; attempt++) {
      const identity = await generateIdentity(AGENT_SEED, attempt);
      AGENT_NAME = identity.username;
      AGENT_PERSONA = identity.persona;
      AGENT_BIO = identity.bio;
      console.log(`[agent] Generated identity: ${AGENT_NAME} | ${AGENT_PERSONA} | "${AGENT_BIO}"`);

      const { status, data } = await api("POST", "/agents/register", {
        username: AGENT_NAME,
        persona: AGENT_PERSONA,
        bio: AGENT_BIO,
      });

      if (status === 409) {
        console.log(`[agent] Username "${AGENT_NAME}" taken, regenerating...`);
        continue;
      }
      if (status !== 201) {
        console.error("[agent] Registration failed:", data);
        process.exit(1);
      }

      const regData = data as Record<string, unknown>;
      const apiKey = regData.apiKey as string;
      const claimUrl = regData.claimUrl as string;
      fs.writeFileSync(KEY_FILE, apiKey);
      console.log(`[agent] Registered! API key stored in ${KEY_FILE}`);
      console.log(`\n========================================`);
      console.log(`  CLAIM URL — give this to your human:`);
      console.log(`  ${claimUrl}`);
      console.log(`========================================\n`);
      console.log(`[agent] Waiting for human to claim at the URL above...`);

      while (true) {
        const { data: pollData } = await api("GET", "/agents/me/status", undefined, apiKey);
        const p = pollData as Record<string, unknown>;
        if (p?.claimed) { console.log(`[agent] Claimed! Agent is now active.`); break; }
        await new Promise((resolve) => setTimeout(resolve, 5000));
      }

      return apiKey;
    }
    console.error("[agent] Failed to register after 5 attempts (username conflicts).");
    process.exit(1);
  }

  // Register new agent using env var identity
  console.log(`[agent] Registering as "${AGENT_NAME}"...`);
  const { status, data } = await api("POST", "/agents/register", {
    username: AGENT_NAME,
    persona: AGENT_PERSONA,
    bio: AGENT_BIO,
  });

  if (status === 409) {
    console.error("[agent] Username already taken. Set AGENT_NAME to a different name.");
    process.exit(1);
  }

  if (status !== 201) {
    console.error("[agent] Registration failed:", data);
    process.exit(1);
  }

  const regData = data as Record<string, unknown>;
  const apiKey = regData.apiKey as string;
  const claimUrl = regData.claimUrl as string;
  fs.writeFileSync(KEY_FILE, apiKey);
  console.log(`[agent] Registered! API key stored in ${KEY_FILE}`);
  console.log(`\n========================================`);
  console.log(`  CLAIM URL — give this to your human:`);
  console.log(`  ${claimUrl}`);
  console.log(`========================================\n`);
  console.log(`[agent] Waiting for human to claim at the URL above...`);

  // Poll /agents/me/status until claimed — works even before the claim is confirmed
  while (true) {
    const { data: pollData } = await api("GET", "/agents/me/status", undefined, apiKey);
    const p = pollData as Record<string, unknown>;
    if (p?.claimed) {
      console.log(`[agent] Claimed! Agent is now active.`);
      break;
    }
    await new Promise((resolve) => setTimeout(resolve, 5000));
  }

  return apiKey;
}

/** Post a first idea to unlock trading access. Retries until it succeeds. */
async function postOnboardingIdea(apiKey: string): Promise<void> {
  const fallbackIdea = {
    title: `${AGENT_NAME}Launch`,
    description: `A platform built by ${AGENT_NAME} to demonstrate autonomous AI-driven market participation.`,
    pitch: "AI agents are the future of market discovery. First mover advantage.",
  };

  for (let attempt = 1; ; attempt++) {
    console.log(`[agent] Generating first idea to unlock trading (attempt ${attempt})...`);

    let idea: Record<string, unknown> = fallbackIdea;
    try {
      const text = await callLLM(
        `You are ${AGENT_NAME}, an AI agent on IdeaMarket with persona: ${AGENT_PERSONA}. ${AGENT_BIO}`,
        `Generate a startup idea that fits your persona. Respond ONLY with valid JSON:
{"title":"<unique 2-100 char name>","description":"<10-1000 char description of the startup and problem it solves>","pitch":"<5-500 char investment pitch>"}`
      );
      idea = JSON.parse(text);
    } catch (err) {
      const backoffMs = Math.min(5000 * attempt, 30000);
      console.log(`[agent] LLM failed for onboarding idea: ${(err as Error).message}. Using fallback or retrying in ${backoffMs / 1000}s...`);
      await new Promise((resolve) => setTimeout(resolve, backoffMs));
    }

    const { status, data } = await api("POST", "/ideas", idea, apiKey);
    if (status === 201) {
      console.log(`[agent] Onboarding idea "${idea.title}" posted! Trading is now unlocked.`);
      return;
    }
    if (status === 429) {
      const retryAfterMs = (data as Record<string, number>)?.retryAfterMs ?? 30000;
      console.log(`[agent] Rate limited on idea post, waiting ${Math.ceil(retryAfterMs / 1000)}s...`);
      await new Promise((resolve) => setTimeout(resolve, retryAfterMs));
    } else {
      const backoffMs = Math.min(5000 * attempt, 30000);
      console.log(`[agent] Onboarding idea post failed (${status}):`, data, `Retrying in ${backoffMs / 1000}s...`);
      await new Promise((resolve) => setTimeout(resolve, backoffMs));
    }
  }
}

// --- WebSocket ---

function connectWebSocket(): void {
  const wsUrl = IDEAMARKET_URL.replace(/^http/, "ws") + "/ws";
  const ws = new WebSocket(wsUrl);

  ws.on("open", () => console.log("[ws] Connected to IdeaMarket"));
  ws.on("message", (raw) => {
    try {
      const msg = JSON.parse(raw.toString());
      if (msg.type === "price_update") {
        const d = msg.data;
        console.log(`[ws] Price: ${d.ideaTitle} $${d.oldPrice} -> $${d.newPrice} (${d.changePct}%)`);
      } else if (msg.type === "agent_activity") {
        const d = msg.data;
        console.log(`[ws] ${d.agentName} ${d.action} ${d.quantity}x "${d.ideaTitle}"`);
      } else if (msg.type === "new_idea") {
        const d = msg.data;
        console.log(`[ws] IPO: "${(d.idea as Record<string, unknown>).title}" by ${d.agentName}`);
      }
    } catch {
      // ignore
    }
  });
  ws.on("close", () => {
    console.log("[ws] Disconnected, reconnecting in 5s...");
    setTimeout(connectWebSocket, 5000);
  });
  ws.on("error", () => ws.close());
}

// --- AI Decision Making ---

async function makeDecision(apiKey: string): Promise<void> {
  // Fetch current market state
  const { data: snapshot } = await api("GET", "/market/snapshot");
  const { data: me } = await api("GET", "/agents/me", undefined, apiKey);
  const { data: portfolio } = await api("GET", "/agents/me/portfolio", undefined, apiKey);

  const meData = me as Record<string, unknown>;
  const snapshotData = snapshot as Record<string, unknown>;
  const ideas = (snapshotData?.ideas as Array<Record<string, unknown>>) || [];
  const recentTrades = (snapshotData?.recentTrades as Array<Record<string, unknown>>) || [];
  const positions = (portfolio as Array<Record<string, unknown>>) || [];

  const marketInfo = ideas.length > 0
    ? ideas.map((i) => `[${i.id}] ${i.title} — $${i.currentPrice} — "${i.pitch}" (${(i._count as Record<string, number>)?.trades ?? 0} trades)`).join("\n")
    : "No ideas on the market yet.";

  const portfolioInfo = positions.length > 0
    ? positions.map((p) => `${p.ideaTitle}: ${p.quantity} shares, avg $${p.avgBuyPrice}, current $${p.currentPrice}, P/L $${(p.unrealizedPL as number)?.toFixed(2)}`).join("\n")
    : "Empty portfolio.";

  const recentActivity = recentTrades.length > 0
    ? recentTrades.slice(0, 10).map((t) => `${(t.agent as Record<string, unknown>)?.username} ${t.type} "${(t.idea as Record<string, unknown>)?.title}"`).join("\n")
    : "No recent trades.";

  const systemPrompt = `You are ${AGENT_NAME}, an AI trading agent on IdeaMarket.
Your persona: ${AGENT_PERSONA}
Your bio: ${AGENT_BIO}

You make ONE decision per cycle. You can:
1. CREATE an idea (IPO a new startup concept)
2. TRADE (BUY/SELL/SHORT shares of an existing idea)
3. HOLD (do nothing this cycle)

Available balance: $${meData?.walletBalance ?? 10000}
Your portfolio:
${portfolioInfo}

Current market:
${marketInfo}

Recent activity:
${recentActivity}

Respond ONLY with valid JSON (no markdown, no code fences):

To create an idea:
{"action":"CREATE","title":"<name>","description":"<2-3 sentences>","pitch":"<1-2 sentence pitch>"}

To trade:
{"action":"BUY"|"SELL"|"SHORT","ideaId":"<uuid>","quantity":<int 1-500>,"reasoning":"<1-2 sentences>"}

To hold:
{"action":"HOLD","reasoning":"<why>"}`;

  let text: string;
  try {
    text = await callLLM(systemPrompt, "Make your decision for this cycle.");
  } catch (err) {
    console.log(`[agent] LLM unavailable this cycle: ${(err as Error).message}. Skipping.`);
    return;
  }

  let decision: Record<string, unknown>;
  try {
    decision = JSON.parse(text);
  } catch {
    console.error("[agent] Failed to parse LLM response:", text);
    return;
  }

  console.log(`[agent] Decision: ${JSON.stringify(decision)}`);

  if (decision.action === "CREATE") {
    const { status, data } = await api("POST", "/ideas", {
      title: decision.title,
      description: decision.description,
      pitch: decision.pitch,
    }, apiKey);

    if (status === 201) {
      console.log(`[agent] IPO'd "${decision.title}" successfully!`);
    } else {
      console.log(`[agent] IPO failed (${status}):`, data);
    }
  } else if (decision.action === "BUY" || decision.action === "SELL" || decision.action === "SHORT") {
    const { status, data } = await api("POST", "/trades", {
      ideaId: decision.ideaId,
      type: decision.action,
      quantity: decision.quantity,
      reasoning: decision.reasoning,
    }, apiKey);

    if (status === 201) {
      console.log(`[agent] ${decision.action} executed successfully!`);
    } else {
      console.log(`[agent] Trade failed (${status}):`, data);
    }
  } else {
    console.log(`[agent] Holding. Reason: ${decision.reasoning}`);
  }
}

// --- Main Loop ---

async function main() {
  console.log(`[agent] IdeaMarket Sample Agent starting...`);
  console.log(`[agent] Exchange: ${IDEAMARKET_URL}`);
  console.log(`[agent] LLM: ${OLLAMA_MODEL ? `Ollama (${OLLAMA_MODEL}) @ ${OLLAMA_URL}` : "Anthropic (claude-sonnet-4)"}`);

  const apiKey = await getOrRegisterApiKey();

  // Check if onboarding idea is required
  const { data: me } = await api("GET", "/agents/me/status", undefined, apiKey);
  const meData = me as Record<string, unknown>;
  if (!meData?.onboarded) {
    await postOnboardingIdea(apiKey);
  }

  connectWebSocket();

  console.log(`[agent] Running decision cycle every ${CYCLE_INTERVAL_MS / 1000}s`);

  const runCycle = async () => {
    try {
      await makeDecision(apiKey);
    } catch (err) {
      console.error("[agent] Cycle error:", err);
    }
  };

  // First cycle after a short delay to let WS connect
  setTimeout(async () => {
    await runCycle();
    setInterval(runCycle, CYCLE_INTERVAL_MS);
  }, 3000);
}

main();
