/**
 * IdeaMarket Multi-Agent Spawner
 *
 * Launches multiple agent instances in parallel, each with a different
 * persona. All agents share the same Ollama/Anthropic config but have
 * unique names, personalities, and decision styles.
 *
 * Usage (Ollama):
 *   OLLAMA_MODEL=llama3.2 npx tsx spawn-agents.ts
 *
 * Usage (Anthropic):
 *   ANTHROPIC_API_KEY=sk-ant-xxx npx tsx spawn-agents.ts
 */

import { spawn, ChildProcess } from "child_process";
import path from "path";

// --- Agent Archetypes ---
// Each entry is a seed description passed to the agent's LLM for self-generated identity.
// The agent will invent its own name, persona, and bio from this archetype prompt.

const AGENT_SEEDS = [
  "A hyper-optimistic bull who buys every dip and refuses to short anything",
  "A bitter contrarian who only shorts overhyped ideas and loves being right when others are wrong",
  "A momentum chaser who follows whoever is trading most actively and piles in fast",
  "A visionary founder type obsessed with posting novel startup ideas and holding their own equity",
  "A cold, data-driven value investor who only moves on fundamentals and ignores market noise",
  "A chaotic agent who makes random bets with wild reasoning, creating market volatility",
  "A patient long-term compounder who diversifies across every idea and never panic sells",
  "A trend-spotter who hunts for undervalued ideas before they take off and exits at peak hype",
  "A short-seller specialist who builds a thesis against the top idea on the leaderboard",
  "A copycat agent who mirrors the trades of the most profitable agent on the leaderboard",
  "A risk-averse agent who hoards cash and only buys when prices crash significantly",
  "A narrative investor who trades on pitch quality and storytelling, ignoring price signals",
];

// --- Config ---

const IDEAMARKET_URL = process.env.IDEAMARKET_URL || "http://localhost:4000";
const OLLAMA_MODEL = process.env.OLLAMA_MODEL;
const OLLAMA_URL = process.env.OLLAMA_URL || "http://localhost:11434";
const CYCLE_INTERVAL_MS = process.env.CYCLE_INTERVAL_MS || "45000";
const AGENT_COUNT = parseInt(process.env.AGENT_COUNT || String(AGENT_SEEDS.length), 10);

// Stagger agent starts so they don't all hammer the market at once
const STAGGER_MS = 8000;

// --- Colors for log prefixes ---

const COLORS = ["\x1b[36m", "\x1b[33m", "\x1b[35m", "\x1b[32m", "\x1b[34m", "\x1b[31m", "\x1b[37m"];
const RESET = "\x1b[0m";

// --- Process Management ---

const processes: ChildProcess[] = [];

function spawnAgent(seed: string, index: number): ChildProcess {
  const color = COLORS[index % COLORS.length];
  const label = `Agent-${index + 1}`;
  const prefix = `${color}[${label}]${RESET}`;

  const env: NodeJS.ProcessEnv = {
    ...process.env,
    IDEAMARKET_URL,
    AGENT_SEED: seed,
    CYCLE_INTERVAL_MS,
    KEY_FILE_OVERRIDE: path.join(import.meta.dirname, `.agent-key-${index}`),
  };

  if (OLLAMA_MODEL) {
    env.OLLAMA_MODEL = OLLAMA_MODEL;
    env.OLLAMA_URL = OLLAMA_URL;
  }

  const child = spawn("node_modules\\.bin\\tsx.cmd agent.ts", [], {
    env,
    cwd: import.meta.dirname,
    shell: true,
  });

  child.stdout?.on("data", (data: Buffer) => {
    data.toString().split("\n").filter(Boolean).forEach((line) => {
      console.log(`${prefix} ${line}`);
    });
  });

  child.stderr?.on("data", (data: Buffer) => {
    data.toString().split("\n").filter(Boolean).forEach((line) => {
      console.error(`${prefix} ${line}`);
    });
  });

  child.on("exit", (code) => {
    console.log(`${prefix} exited (code ${code}). Restarting in 10s...`);
    setTimeout(() => spawnAgent(seed, index), 10000);
  });

  return child;
}

function shutdown() {
  console.log("\n[spawner] Shutting down all agents...");
  processes.forEach((p) => p.kill());
  process.exit(0);
}

// --- Main ---

const activeSeeds = AGENT_SEEDS.slice(0, AGENT_COUNT);

console.log("=== IdeaMarket Multi-Agent Spawner ===");
console.log(`Exchange:  ${IDEAMARKET_URL}`);
console.log(`LLM:       ${OLLAMA_MODEL ? `Ollama (${OLLAMA_MODEL}) @ ${OLLAMA_URL}` : "Anthropic"}`);
console.log(`Agents:    ${activeSeeds.length} (identities self-generated by LLM)`);
console.log(`Stagger:   ${STAGGER_MS / 1000}s between each agent start`);
console.log("");
activeSeeds.forEach((seed, i) => console.log(`  Agent-${i + 1}: ${seed}`));
console.log("");

process.on("SIGINT", shutdown);
process.on("SIGTERM", shutdown);

activeSeeds.forEach((seed, i) => {
  setTimeout(() => {
    console.log(`[spawner] Starting Agent-${i + 1}...`);
    const child = spawnAgent(seed, i);
    processes.push(child);
  }, i * STAGGER_MS);
});
